### ISSUE TITLE
Add protolib as a git submodule

### ISSUE THREAD

**Issue by jordanauge** [USNavalResearchLaboratory/mgen#13]
Hello,

When building older releases through tags, there is no easy way to know which version of protolib was used at the time of the release. Using submodules would simplify this task.

Cheers,
Jordan

**Comment by weston-nrl** [comment]
Correct.  Current releases/tags predate our use of GitHub, and have associated source code uploads that include protolib from the time when the release was made.

**Comment by ljt-git** [comment]
It looks like this fix was never merged.  

I applied the changes cloned mgen; cd mgen; git submodule update --init 

but no protolib was downloaded.  

Is this the correct usage?  I am testing on osx.

**Comment by weston-nrl** [comment]
You can also add '--recursive' to your git clone command to do it in a single step.

But no, this has not been done (and I don't think there is anything to merge -- this is just a suggestion that someone would need to implement).  This has been done successfully in NORM, but not in MGEN yet.  I'm not sure of the reason for that.
