### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by bsureshkum** [USNavalResearchLaboratory/mgen#36]
Hi,
Would you please help me in sorting out the following error. I was trying to install these code in Kali Linux. Thanks.
--------------------------------------
$ make -f Makefile.linux
g++ -c -g -DPROTO_DEBUG -DHAVE_GPS -DUNIX -Wall -Wcast-align -fPIC -DLINUX -DHAVE_SCHED -DHAVE_GETLOGIN -DHAVE_LOCKF -DHAVE_DIRFD -DHAVE_ASSERT  -D_FILE_OFFSET_BITS=64 -DUNIX -DUSE_SELECT -DUSE_TIMERFD -DHAVE_PSELECT -DHAVE_IPV6 -DHAVE_PCAP -I/usr/X11R6/include  -I../makefiles -I../include -I../protolib/include  -o ../src/common/mgenApp.o ../src/common/mgenApp.cpp
In file included from ../include/mgenEvent.h:5,
                 from ../include/mgenFlow.h:4,
                 from ../include/mgen.h:7,
                 from ../src/common/mgenApp.cpp:2:
../include/mgenPattern.h:7:10: fatal error: pcap.h: No such file or directory
    7 | #include <pcap.h>      // for CLONE tcpdump files
      |          ^~~~~~~~
compilation terminated.
make: *** [Makefile.common:30: ../src/common/mgenApp.o] Error 1
----------------------------------------

**Comment by weston-nrl** [comment]
You need to install the libpcap development libraries.  'sudo apt-get install libpcap-dev' or whatever is appropriate for your distro.

**Comment by bsureshkum** [comment]
Thanks Jeff. It worked. But I had a similar problem with windows machine as well. I hope to solve the problem myself.
Kind Regards,Suresh
    On Thursday, 4 November, 2021, 06:51:34 pm GMT, Jeff Weston ***@***.***> wrote:  
 
 


You need to install the libpcap development libraries. 'sudo apt-get install libpcap-dev' or whatever is appropriate for your distro.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by bsureshkum** [comment]
Thank you Jeff. Apologies, I didn’t close the case.

Kind Regards,
Suresh
