### ISSUE TITLE
TCP retry handles flow ID incorrectly

### ISSUE THREAD

**Issue by aamcintosh** [USNavalResearchLaboratory/mgen#56]
In TCP retry mode, the following
```
0.0 ON 10 TCP DST 172.16.1.12/6767 PERIODIC [2 1400] COUNT 1498
```
results in the error message
```
Mgen::ParseEvent() Error: invalid <flowId> at line: 0
```
This appears to be due to the following code at line 1142 of common/mgenTransport.cpp:
```
sprintf(cmd, "%x MOD %x RECONNECT", (unsigned int) GetRetryDelay(), next->GetFlowId());
```
The second %x should be a %d just as it is on line 1138:
```
sprintf(cmd, "MOD %d PAUSE", next->GetFlowId());
```
Strange behavior also ensues if the flow ID expressed as a hexadecimal number containing no letters.

**Comment by weston-nrl** [comment]
Should be fixed, please let me know if it works for you. I updated both of those lines as they should be unsigned ints.

**Comment by aamcintosh** [comment]
Yes, that seems to have fixed the problem.  Thank you.
