### ISSUE TITLE
Does ubuntu16.04 support MGEN？

### ISSUE THREAD

**Issue by shu-siyue** [USNavalResearchLaboratory/mgen#8]
Does ubuntu16.04 support MGEN？

**Comment by szl0144** [comment]
Yes, I have used MGEN with EMANE in ubuntu 14.04 and 16.04, I think it's also available for 18.04.

**Comment by weston-nrl** [comment]
Yes, I regularly compile on both Ubuntu 16.04 and 18.04.  Sorry, did not see this question previously
