### ISSUE TITLE
Questions about Multi-hop network topology mgen configuration

### ISSUE THREAD

**Issue by szl0144** [USNavalResearchLaboratory/mgen#9]
Hi,

I am run a demo with 3 nodes multi-hop network topology in EMANE, I use multicast address 225.1.20.1/5001 as destination in mgen. I have changed the path loss between node1 node2 and node 3 to achieve a topology to let node 1 transmit packet through relay node2 to node3 rather than transmit packet directly to node3. Because mgen sends packets to all of three nodes, but I want to just let mgen send packet to node 1 and node 1 deliver packets to node 3 through node 2. I don't know how to use a unicast address to let mgen send packet to node 1 firstly, and packets are sent to node 3 through node 2 next  my topology. Can you give me some ideas?

The following figure may describe my topology clearly.
![topology](https://user-images.githubusercontent.com/40918217/83683804-9110a800-a5ab-11ea-9c04-177640238260.jpg)

Thank you very much.

Best,
Shaoyi

**Comment by weston-nrl** [comment]
What you are looking for, regardless of whether you use unicast or multicast, is called [routing](https://en.wikipedia.org/wiki/Routing).  There are many types (e.g. static routing, dynamic routing) and methods/algorithms.  They can work different ways (e.g. in some cases multiple interfaces are required), I suggest reading up on it.

**Comment by szl0144** [comment]
I see, thank you for your suggestion. I just checked the static routing and dynamic routing, I am looking for a static routing from mgen to node 3 through node 1 and node2. Do you mean I need to implement some routing algorithm in EMANE?

**Comment by weston-nrl** [comment]
No.  EMANE emulates wireless links between nodes.  What those end systems do with those packets (generation, reception, forwarding/routing) has nothing to do with EMANE.  They are done using the exact same methods and protocols/executables that you would use on the real physical system/network without EMANE.  The commands are identical whether the interface is an EMANE interface or a real physical interface.

For static routing, you just need to add the appropriate static routes to each node's routing table (e.g. for linux, Google the 'route' and/or 'ip route' commands).

**Comment by szl0144** [comment]
I see, sorry about some misunderstandings about the IP routing part. I think your explanation of manually routing configuration is clear to me, thank you for your help!
